package com.example.compiler.syntaxer;

public enum FormalGrammar {
    PROGRAM,
    CLASS_DECLARATION,
    CLASS_NAME,
    MEMBER_DECLARATION,
    VARIABLE_DECLARATION,
    METHOD_DECLARATION,
    PARAMETERS,
    PARAMETER_DECLARATION,
    BODY,
    CONSTRUCTOR_DECLARATION,
    STATEMENT,
    ASSIGNMENT,
    WHILE_LOOP,
    IF_STATEMENT,
    RETURN_STATEMENT,
    EXPRESSION,
    ARGUMENTS,
    PRIMARY,
    IDENTIFIER
}
